name: Import SARIF
on:
  push:
    branches: [ master ]
      
jobs:                                                  
  Import-SARIF:
    runs-on: ubuntu-latest

    steps:
      # Import SARIF to GitHub Security Code Scanning
      - name: Import Results
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ./sarif/output.sarif
